#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=true
org.gradle.configuration-cache=false
#Kotlin
kotlin.code.style=official
#MPP
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin/JS
# Use npm instead of Yarn for Kotlin/JS dependencies
kotlin.js.yarn=false

# Apple
# Suppress Xcode compatibility warning
kotlin.apple.xcodeCompatibility.nowarn=true
